### ISSUE TITLE
Please don't colour code game compatibility.

### ISSUE THREAD

**Issue by andreacampanella** [paulocode/picostation#11]
Colours are not the best solution to show compatibility, as a colourblind person I can't understand the difference between this two for example: 

🟢 - Fully playable, no glitches nor extended load times

🟡 - Fully playable but sometimes with extended load times

for me are the same colour, please use number or symbols.

Thanks!

**Comment by airainchoc** [comment]
Sorry about that, it's corrected (0🔴/1🟠/2🟡/3🟢)

**Comment by ramapcsx2** [comment]
Hey ho,
if I may add a suggestion.. :p 

You don't need a compatibility list. The way this ODE will eventually work makes it so that you can expect 100% compatibility, with only some known problem games requiring fine tuning of some parameters.
So instead of having a list at this stage, it'll be better to work on the project more, and get it into functional state.
Then you could have a list of "games with problems still", which will be quite small and manageable ;p

**Comment by airainchoc** [comment]
Hey hey, 
I agree with you, and treat this more as a "tried games" page

As sadly I'm not a dev myself, I can only help the project by keeping the git updated while talented people are working under the radar to make it work better

**Comment by ramapcsx2** [comment]
Try to find the other people (usually Discord these days), and watch what they're doing. 
You can learn how to code stuff, maybe it's something you'll enjoy :)
